/**
 * ScrapingDog API Catalog
 *
 * Maps our tool IDs to ScrapingDog-specific endpoints and params.
 * This is the only file that knows about ScrapingDog URLs.
 */

import type { PremiumApiEntry } from "../../types.js";

export interface ScrapingDogApiEntry extends PremiumApiEntry {
  endpoint: string;
  method?: "GET" | "POST";
}

export const SCRAPINGDOG_APIS: ScrapingDogApiEntry[] = [
  // ── Web Scraping ──────────────────────────────────────────────
  {
    id: "web_scrape",
    name: "Web Scraping API",
    description: "Scrape any website's HTML content. Handles proxies, CAPTCHAs, and JavaScript rendering. Supports POST with custom headers and body.",
    creditCost: 1,
    category: "scraping",
    endpoint: "https://api.scrapingdog.com/scrape",
    requiredParams: ["url"],
    optionalParams: ["dynamic", "premium", "country"],
    cache: { mode: "enrich", type: "web_page" },
  },
  {
    id: "web_scrape_post",
    name: "Web Scraping API (POST)",
    description: "POST version of web scraping — send custom headers and body to the target URL. Pass 'body' (string) and 'headers' (JSON string of key-value pairs).",
    creditCost: 1,
    category: "scraping",
    endpoint: "https://api.scrapingdog.com/scrape",
    method: "POST",
    requiredParams: ["url"],
    optionalParams: ["dynamic", "premium", "country", "body", "headers"],
    cache: { mode: "enrich", type: "web_page" },
  },
  {
    id: "screenshot",
    name: "Screenshot API",
    description: "Take a full-page screenshot of any URL. Returns the image URL.",
    creditCost: 5,
    category: "scraping",
    endpoint: "https://api.scrapingdog.com/screenshot",
    requiredParams: ["url"],
    optionalParams: ["full_page", "width", "height"],
    cache: { mode: "raw", type: "image_description" },
  },

  // ── Search ────────────────────────────────────────────────────
  {
    id: "google_search",
    name: "Google Search (SERP) API",
    description: "Get Google search results as structured JSON. Includes titles, URLs, descriptions, and featured snippets.",
    creditCost: 5,
    category: "search",
    endpoint: "https://api.scrapingdog.com/google",
    requiredParams: ["query"],
    optionalParams: ["country", "language", "results"],
    cache: { mode: "raw", type: "web_search" },
  },
  {
    id: "google_ai_mode",
    name: "Google AI Mode API",
    description: "Get Google AI Mode results — AI-generated answers with sources and follow-up suggestions.",
    creditCost: 10,
    category: "search",
    endpoint: "https://api.scrapingdog.com/google_ai_mode",
    requiredParams: ["query"],
    optionalParams: ["country", "language"],
    cache: { mode: "enrich", type: "web_search" },
  },
  {
    id: "google_ai_overview",
    name: "Google AI Overview API",
    description: "Get Google AI Overview (SGE) snippets — the AI-generated summaries at the top of search results.",
    creditCost: 10,
    category: "search",
    endpoint: "https://api.scrapingdog.com/google_ai_overview",
    requiredParams: ["query"],
    optionalParams: ["country", "language"],
    cache: { mode: "enrich", type: "web_search" },
  },
  {
    id: "google_autocomplete",
    name: "Google Autocomplete API",
    description: "Get Google Autocomplete suggestions for a query — useful for keyword research and content ideas.",
    creditCost: 5,
    category: "search",
    endpoint: "https://api.scrapingdog.com/google_autocomplete",
    requiredParams: ["query"],
    optionalParams: ["country", "language"],
    cache: { mode: "raw", type: "web_search" },
  },
  {
    id: "bing_search",
    name: "Bing Search Scraper API",
    description: "Get Bing search results as structured JSON.",
    creditCost: 5,
    category: "search",
    endpoint: "https://api.scrapingdog.com/bing",
    requiredParams: ["query"],
    optionalParams: ["country", "language"],
    cache: { mode: "raw", type: "web_search" },
  },
  {
    id: "duckduckgo_search",
    name: "DuckDuckGo Scraper API",
    description: "Get DuckDuckGo search results as structured JSON.",
    creditCost: 5,
    category: "search",
    endpoint: "https://api.scrapingdog.com/duckduckgo",
    requiredParams: ["query"],
    optionalParams: [],
    cache: { mode: "raw", type: "web_search" },
  },
  {
    id: "universal_search",
    name: "Universal Search API",
    description: "Scrape any search engine with a single API. Supports Google, Bing, Yahoo, Yandex, and more.",
    creditCost: 20,
    category: "search",
    endpoint: "https://api.scrapingdog.com/universal_search",
    requiredParams: ["query"],
    optionalParams: ["engine", "country", "language"],
    cache: { mode: "raw", type: "web_search" },
  },
  {
    id: "baidu_search",
    name: "Baidu Scraper API",
    description: "Get Baidu (Chinese search engine) results as structured JSON.",
    creditCost: 5,
    category: "search",
    endpoint: "https://api.scrapingdog.com/baidu",
    requiredParams: ["query"],
    optionalParams: [],
    cache: { mode: "raw", type: "web_search" },
  },

  // ── News ──────────────────────────────────────────────────────
  {
    id: "google_news",
    name: "Google News API",
    description: "Get Google News articles for a query. Returns headlines, sources, timestamps, and URLs.",
    creditCost: 5,
    category: "news",
    endpoint: "https://api.scrapingdog.com/google_news",
    requiredParams: ["query"],
    optionalParams: ["country", "language"],
    cache: { mode: "raw", type: "web_search" },
  },

  // ── Images & Visual ───────────────────────────────────────────
  {
    id: "google_images",
    name: "Google Images API",
    description: "Get Google Image search results with image URLs, titles, and source pages.",
    creditCost: 10,
    category: "images",
    endpoint: "https://api.scrapingdog.com/google_images",
    requiredParams: ["query"],
    optionalParams: ["country", "language"],
    cache: { mode: "raw", type: "web_search" },
  },
  {
    id: "google_lens",
    name: "Google Lens API",
    description: "Get Google Lens visual search results for an image URL.",
    creditCost: 5,
    category: "images",
    endpoint: "https://api.scrapingdog.com/google_lens",
    requiredParams: ["url"],
    optionalParams: ["country", "language"],
    cache: { mode: "raw", type: "image_description" },
  },

  // ── Video ─────────────────────────────────────────────────────
  {
    id: "google_videos",
    name: "Google Videos API",
    description: "Get Google Video search results with titles, thumbnails, durations, and source URLs.",
    creditCost: 5,
    category: "video",
    endpoint: "https://api.scrapingdog.com/google_videos",
    requiredParams: ["query"],
    optionalParams: ["country", "language"],
    cache: { mode: "raw", type: "web_search" },
  },
  {
    id: "google_shorts",
    name: "Google Shorts API",
    description: "Get Google Shorts video results.",
    creditCost: 5,
    category: "video",
    endpoint: "https://api.scrapingdog.com/google_shorts",
    requiredParams: ["query"],
    optionalParams: ["country", "language"],
    cache: { mode: "raw", type: "web_search" },
  },
  {
    id: "youtube_search",
    name: "YouTube Search API",
    description: "Search YouTube videos. Returns titles, channels, view counts, and video URLs.",
    creditCost: 5,
    category: "video",
    endpoint: "https://api.scrapingdog.com/youtube/search",
    requiredParams: ["query"],
    optionalParams: [],
    cache: { mode: "raw", type: "web_search" },
  },
  {
    id: "youtube_transcript",
    name: "YouTube Transcript API",
    description: "Get the full transcript/captions of a YouTube video.",
    creditCost: 1,
    category: "video",
    endpoint: "https://api.scrapingdog.com/youtube/transcript",
    requiredParams: ["video_id"],
    optionalParams: ["language"],
    cache: { mode: "enrich", type: "video_transcript" },
  },
  {
    id: "youtube_channel",
    name: "YouTube Channel API",
    description: "Get YouTube channel info including subscriber count, video list, and about data.",
    creditCost: 5,
    category: "video",
    endpoint: "https://api.scrapingdog.com/youtube/channel",
    requiredParams: ["url"],
    optionalParams: [],
    cache: { mode: "enrich", type: "api_response" },
  },
  {
    id: "youtube_comments",
    name: "YouTube Comments API",
    description: "Get comments from a YouTube video.",
    creditCost: 5,
    category: "video",
    endpoint: "https://api.scrapingdog.com/youtube/comments",
    requiredParams: ["video_id"],
    optionalParams: [],
    cache: { mode: "enrich", type: "api_response" },
  },

  // ── E-Commerce ────────────────────────────────────────────────
  {
    id: "amazon_search",
    name: "Amazon Search API",
    description: "Search Amazon products. Returns titles, prices, ratings, and product URLs.",
    creditCost: 1,
    category: "ecommerce",
    endpoint: "https://api.scrapingdog.com/amazon/search",
    requiredParams: ["query"],
    optionalParams: ["country", "page"],
    cache: { mode: "raw", type: "api_response" },
  },
  {
    id: "amazon_product",
    name: "Amazon Product API",
    description: "Get detailed Amazon product information including description, specs, reviews, and pricing.",
    creditCost: 1,
    category: "ecommerce",
    endpoint: "https://api.scrapingdog.com/amazon/product",
    requiredParams: ["asin"],
    optionalParams: ["country"],
    cache: { mode: "enrich", type: "api_response" },
  },
  {
    id: "walmart_search",
    name: "Walmart Scraper API",
    description: "Scrape Walmart product and search pages. Returns structured product data.",
    creditCost: 5,
    category: "ecommerce",
    endpoint: "https://api.scrapingdog.com/walmart",
    requiredParams: ["url"],
    optionalParams: [],
    cache: { mode: "raw", type: "api_response" },
  },
  {
    id: "ebay_search",
    name: "eBay Scraper API",
    description: "Scrape eBay listings. Returns product titles, prices, bids, and seller info.",
    creditCost: 5,
    category: "ecommerce",
    endpoint: "https://api.scrapingdog.com/ebay",
    requiredParams: ["url"],
    optionalParams: [],
    cache: { mode: "raw", type: "api_response" },
  },
  {
    id: "flipkart_search",
    name: "Flipkart Scraper API",
    description: "Scrape Flipkart (Indian e-commerce) product and search pages.",
    creditCost: 5,
    category: "ecommerce",
    endpoint: "https://api.scrapingdog.com/flipkart",
    requiredParams: ["url"],
    optionalParams: [],
    cache: { mode: "raw", type: "api_response" },
  },
  {
    id: "myntra_search",
    name: "Myntra Scraper API",
    description: "Scrape Myntra (Indian fashion e-commerce) product and search pages.",
    creditCost: 5,
    category: "ecommerce",
    endpoint: "https://api.scrapingdog.com/myntra",
    requiredParams: ["url"],
    optionalParams: [],
    cache: { mode: "raw", type: "api_response" },
  },

  // ── Social & Professional ─────────────────────────────────────
  {
    id: "linkedin_profile",
    name: "LinkedIn Profile Scraper API",
    description: "Get LinkedIn profile data including experience, education, and skills. Expensive — 50 credits (100 if protected profile).",
    creditCost: 50,
    category: "social",
    endpoint: "https://api.scrapingdog.com/linkedin",
    requiredParams: ["url"],
    optionalParams: [],
    cache: { mode: "enrich", type: "api_response" },
  },
  {
    id: "linkedin_jobs",
    name: "LinkedIn Jobs Scraper API",
    description: "Scrape LinkedIn job listings. Returns job titles, companies, locations, and descriptions.",
    creditCost: 5,
    category: "social",
    endpoint: "https://api.scrapingdog.com/linkedin_jobs",
    requiredParams: ["url"],
    optionalParams: [],
    cache: { mode: "raw", type: "api_response" },
  },
  {
    id: "twitter_search",
    name: "X/Twitter Scraper API",
    description: "Search X (Twitter) posts. Returns tweets, authors, engagement metrics.",
    creditCost: 5,
    category: "social",
    endpoint: "https://api.scrapingdog.com/twitter",
    requiredParams: ["query"],
    optionalParams: [],
    cache: { mode: "raw", type: "web_search" },
  },

  // ── Maps & Local ──────────────────────────────────────────────
  {
    id: "google_maps",
    name: "Google Maps API",
    description: "Get Google Maps business listings with ratings, addresses, phone numbers, and reviews.",
    creditCost: 5,
    category: "local",
    endpoint: "https://api.scrapingdog.com/google_maps",
    requiredParams: ["query"],
    optionalParams: ["country", "language", "ll"],
    cache: { mode: "raw", type: "api_response" },
  },
  {
    id: "google_local",
    name: "Google Local API",
    description: "Get Google Local business results with detailed info, reviews, and contact details.",
    creditCost: 5,
    category: "local",
    endpoint: "https://api.scrapingdog.com/google_local",
    requiredParams: ["query"],
    optionalParams: ["country", "language"],
    cache: { mode: "raw", type: "api_response" },
  },
  {
    id: "yelp_search",
    name: "Yelp Scraper API",
    description: "Search Yelp for businesses with ratings, reviews, and contact info.",
    creditCost: 1,
    category: "local",
    endpoint: "https://api.scrapingdog.com/yelp",
    requiredParams: ["query"],
    optionalParams: ["location"],
    cache: { mode: "raw", type: "api_response" },
  },

  // ── Finance ───────────────────────────────────────────────────
  {
    id: "google_finance",
    name: "Google Finance API",
    description: "Get Google Finance stock data including price, change, market cap, and related news.",
    creditCost: 5,
    category: "finance",
    endpoint: "https://api.scrapingdog.com/google_finance",
    requiredParams: ["query"],
    optionalParams: [],
    cache: { mode: "raw", type: "api_response" },
  },
  {
    id: "google_trends",
    name: "Google Trends API",
    description: "Get Google Trends data for a query. Shows interest over time and related queries.",
    creditCost: 5,
    category: "finance",
    endpoint: "https://api.scrapingdog.com/google_trends",
    requiredParams: ["query"],
    optionalParams: ["country"],
    cache: { mode: "enrich", type: "api_response" },
  },

  // ── Shopping ──────────────────────────────────────────────────
  {
    id: "google_shopping",
    name: "Google Shopping API",
    description: "Get Google Shopping product listings with prices, ratings, and merchant info.",
    creditCost: 5,
    category: "shopping",
    endpoint: "https://api.scrapingdog.com/google_shopping",
    requiredParams: ["query"],
    optionalParams: ["country", "language"],
    cache: { mode: "raw", type: "api_response" },
  },
  {
    id: "google_product",
    name: "Google Product API",
    description: "Get detailed Google Product information for a specific product.",
    creditCost: 5,
    category: "shopping",
    endpoint: "https://api.scrapingdog.com/google_product",
    requiredParams: ["product_id"],
    optionalParams: ["country", "language"],
    cache: { mode: "enrich", type: "api_response" },
  },
  {
    id: "google_immersive_product",
    name: "Google Immersive Product API",
    description: "Get Google Immersive Product data with rich product details, images, and merchant comparisons.",
    creditCost: 5,
    category: "shopping",
    endpoint: "https://api.scrapingdog.com/google_immersive_product",
    requiredParams: ["product_id"],
    optionalParams: ["country", "language"],
    cache: { mode: "enrich", type: "api_response" },
  },

  // ── Academic & Patents ────────────────────────────────────────
  {
    id: "google_scholar",
    name: "Google Scholar API",
    description: "Search Google Scholar for academic papers, citations, and research articles.",
    creditCost: 5,
    category: "academic",
    endpoint: "https://api.scrapingdog.com/google_scholar",
    requiredParams: ["query"],
    optionalParams: ["country", "language"],
    cache: { mode: "enrich", type: "web_search" },
  },
  {
    id: "google_patents",
    name: "Google Patents API",
    description: "Search Google Patents for patent documents, claims, and citations.",
    creditCost: 5,
    category: "academic",
    endpoint: "https://api.scrapingdog.com/google_patents",
    requiredParams: ["query"],
    optionalParams: ["country", "language"],
    cache: { mode: "enrich", type: "web_search" },
  },

  // ── Jobs & Real Estate ────────────────────────────────────────
  {
    id: "google_jobs",
    name: "Google Jobs API",
    description: "Get Google Jobs listings for a query. Returns job titles, companies, locations, and descriptions.",
    creditCost: 5,
    category: "jobs",
    endpoint: "https://api.scrapingdog.com/google_jobs",
    requiredParams: ["query"],
    optionalParams: ["country", "language"],
    cache: { mode: "raw", type: "api_response" },
  },
  {
    id: "indeed_search",
    name: "Indeed Scraper API",
    description: "Scrape Indeed job listings. Pass an Indeed search/job URL to get structured job data.",
    creditCost: 1,
    category: "jobs",
    endpoint: "https://api.scrapingdog.com/indeed",
    requiredParams: ["url"],
    optionalParams: [],
    cache: { mode: "raw", type: "api_response" },
  },
  {
    id: "google_hotels",
    name: "Google Hotels API",
    description: "Get Google Hotels listings with prices, ratings, amenities, and availability.",
    creditCost: 5,
    category: "travel",
    endpoint: "https://api.scrapingdog.com/google_hotels",
    requiredParams: ["query"],
    optionalParams: ["country", "language"],
    cache: { mode: "raw", type: "api_response" },
  },
  {
    id: "zillow_search",
    name: "Zillow Scraper API",
    description: "Scrape Zillow real estate listings. Pass a Zillow search/property URL to get structured data.",
    creditCost: 5,
    category: "realestate",
    endpoint: "https://api.scrapingdog.com/zillow",
    requiredParams: ["url"],
    optionalParams: [],
    cache: { mode: "enrich", type: "api_response" },
  },
];
