/**
 * Discord Setup & Management Tool Definitions
 */

import type { DotBotTool } from "../../memory/types.js";

export const discordTools: DotBotTool[] = [
  {
    id: "discord.validate_token",
    name: "validate_discord_token",
    description: "Validate a Discord bot token by calling the Discord API. Returns the bot's username, ID, and application ID if valid. The token can come from: (1) the encrypted vault (stored by secrets.prompt_user — preferred), (2) an explicit token argument, or (3) process.env. On success, the token is auto-stored in the vault for future use.",
    source: "core",
    category: "discord",
    executor: "local",
    runtime: "internal",
    credentialRequired: "DISCORD_BOT_TOKEN",
    inputSchema: {
      type: "object",
      properties: {
        token: { type: "string", description: "Optional. The Discord bot token — only needed if not already stored via secrets.prompt_user." },
      },
    },
    annotations: { readOnlyHint: true, verificationHint: true, mutatingHint: false },
  },
  {
    id: "discord.get_invite_url",
    name: "get_discord_invite_url",
    description: "Generate the OAuth2 invite URL for adding the bot to a Discord server. Uses the bot's application ID (auto-detected from stored token if not provided). The user opens this URL in their browser to add the bot to their server.",
    source: "core",
    category: "discord",
    executor: "local",
    runtime: "internal",
    credentialRequired: "DISCORD_BOT_TOKEN",
    inputSchema: {
      type: "object",
      properties: {
        application_id: { type: "string", description: "Discord application/client ID. If omitted, auto-detected from the stored bot token." },
        permissions: { type: "string", description: "Permission integer (default: '8' = Administrator). Use '8' for full access." },
      },
    },
    annotations: { readOnlyHint: true, verificationHint: true, mutatingHint: false },
  },
  {
    id: "discord.list_guilds",
    name: "list_discord_guilds",
    description: "List all Discord servers (guilds) the bot has been added to. Uses the stored bot token. Run this after the user invites the bot to verify it's in the right server.",
    source: "core",
    category: "discord",
    executor: "local",
    runtime: "internal",
    credentialRequired: "DISCORD_BOT_TOKEN",
    inputSchema: {
      type: "object",
      properties: {},
    },
    annotations: { readOnlyHint: true, verificationHint: true, mutatingHint: false },
  },
  {
    id: "discord.list_channels",
    name: "list_discord_channels",
    description: "List all channels in a Discord server. Returns channel names, IDs, and types (text/voice/category).",
    source: "core",
    category: "discord",
    executor: "local",
    runtime: "internal",
    credentialRequired: "DISCORD_BOT_TOKEN",
    inputSchema: {
      type: "object",
      properties: {
        guild_id: { type: "string", description: "The Discord server (guild) ID" },
      },
      required: ["guild_id"],
    },
    annotations: { readOnlyHint: true, verificationHint: true, mutatingHint: false },
  },
  {
    id: "discord.create_channel",
    name: "create_discord_channel",
    description: "Create a new text channel in a Discord server. Requires the bot to have Manage Channels permission.",
    source: "core",
    category: "discord",
    executor: "local",
    runtime: "internal",
    credentialRequired: "DISCORD_BOT_TOKEN",
    inputSchema: {
      type: "object",
      properties: {
        guild_id: { type: "string", description: "The Discord server (guild) ID" },
        name: { type: "string", description: "Channel name (lowercase, no spaces — Discord normalizes automatically)" },
        topic: { type: "string", description: "Optional channel topic/description" },
      },
      required: ["guild_id", "name"],
    },
    annotations: { destructiveHint: true, mutatingHint: true },
  },
  {
    id: "discord.setup_channels",
    name: "setup_discord_channels",
    description: "All-in-one: creates the three standard DotBot channels (#conversation, #updates, #logs) in a Discord server. Skips any that already exist. Returns the channel IDs ready for discord.write_config.",
    source: "core",
    category: "discord",
    executor: "local",
    runtime: "internal",
    credentialRequired: "DISCORD_BOT_TOKEN",
    inputSchema: {
      type: "object",
      properties: {
        guild_id: { type: "string", description: "The Discord server (guild) ID" },
      },
      required: ["guild_id"],
    },
    annotations: { destructiveHint: true, mutatingHint: true },
  },
  {
    id: "discord.write_config",
    name: "write_discord_config",
    description: "Write Discord configuration (guild ID, channel IDs) to ~/.bot/.env. The bot token is read from the encrypted vault (stored there by discord.validate_token). Only non-sensitive config is written to .env.",
    source: "core",
    category: "discord",
    executor: "local",
    runtime: "internal",
    credentialRequired: "DISCORD_BOT_TOKEN",
    inputSchema: {
      type: "object",
      properties: {
        guild_id: { type: "string", description: "The Discord server (guild) ID" },
        channel_conversation: { type: "string", description: "Channel ID for #conversation" },
        channel_updates: { type: "string", description: "Channel ID for #updates" },
        channel_logs: { type: "string", description: "Channel ID for #logs" },
      },
      required: ["guild_id", "channel_conversation", "channel_updates", "channel_logs"],
    },
    annotations: { destructiveHint: true, mutatingHint: true },
  },
  {
    id: "discord.create_guild",
    name: "create_discord_guild",
    description: "Create a new Discord server (guild) owned by the bot. The bot automatically becomes the server owner — no invite needed. Only works for bots in fewer than 10 servers. Returns the guild ID for use with discord.setup_channels.",
    source: "core",
    category: "discord",
    executor: "local",
    runtime: "internal",
    credentialRequired: "DISCORD_BOT_TOKEN",
    inputSchema: {
      type: "object",
      properties: {
        name: { type: "string", description: "Server name (default: 'Agent HQ')" },
      },
    },
    annotations: { destructiveHint: true, mutatingHint: true },
  },
  {
    id: "discord.create_invite",
    name: "create_discord_invite",
    description: "Create an invite link for a Discord channel. Returns the invite URL and a QR code URL the user can scan from their phone to join via the Discord mobile app. By default creates a permanent, unlimited-use invite.",
    source: "core",
    category: "discord",
    executor: "local",
    runtime: "internal",
    credentialRequired: "DISCORD_BOT_TOKEN",
    inputSchema: {
      type: "object",
      properties: {
        channel_id: { type: "string", description: "The channel ID to create the invite for" },
        max_age: { type: "number", description: "Invite expiry in seconds (0 = never, default: 0)" },
        max_uses: { type: "number", description: "Max number of uses (0 = unlimited, default: 0)" },
      },
      required: ["channel_id"],
    },
    annotations: { destructiveHint: true, mutatingHint: true },
  },
  {
    id: "discord.send_message",
    name: "send_discord_message",
    description: "Send a message to a Discord channel with optional rich embeds and link buttons. Embeds support titles, descriptions, colors, fields, images, and thumbnails. Link buttons appear below the message as clickable URL buttons.",
    source: "core",
    category: "discord",
    executor: "local",
    runtime: "internal",
    credentialRequired: "DISCORD_BOT_TOKEN",
    inputSchema: {
      type: "object",
      properties: {
        channel_id: { type: "string", description: "The Discord channel ID to send the message to" },
        content: { type: "string", description: "The message text to send (supports Discord markdown). Optional if embeds provided." },
        embeds: {
          type: "array",
          description: "Array of embed objects for rich formatting. Each embed can have: title, description, url, color (decimal int, e.g. 5814783 for cyan), fields (array of {name, value, inline?}), image ({url}), thumbnail ({url}), author ({name, url?, icon_url?}), footer ({text, icon_url?}), timestamp (ISO 8601 string)",
          items: { type: "object" },
        },
        link_buttons: {
          type: "array",
          description: "Array of URL link buttons to display below the message. Each button: {label (string, button text), url (string, opens in browser), emoji? (string, optional Unicode emoji before label)}. Max 5 buttons per row, max 5 rows.",
          items: { type: "object" },
        },
        action_buttons: {
          type: "array",
          description: "Array of interactive buttons that trigger actions when clicked. Each button: {label (string), custom_id (string, use 'prompt:your text' to trigger a DotBot prompt), style? ('primary'|'secondary'|'success'|'danger', default: 'primary'), emoji? (string, optional Unicode emoji)}. Max 5 buttons per row, max 5 rows.",
          items: { type: "object" },
        },
      },
      required: ["channel_id"],
    },
    annotations: { mutatingHint: true },
  },
  {
    id: "discord.send_file",
    name: "send_discord_file",
    description: "Upload a file (image, document, etc.) to a Discord channel with an optional message. Reads the file from the local filesystem and uploads it as an attachment. Supports any file type — images will render inline in Discord. Max file size: 8MB (Discord free tier limit).",
    source: "core",
    category: "discord",
    executor: "local",
    runtime: "internal",
    credentialRequired: "DISCORD_BOT_TOKEN",
    inputSchema: {
      type: "object",
      properties: {
        channel_id: { type: "string", description: "The Discord channel ID to send the file to" },
        file_path: { type: "string", description: "Absolute path to the file to upload" },
        content: { type: "string", description: "Optional message text to send alongside the file" },
      },
      required: ["channel_id", "file_path"],
    },
    annotations: { mutatingHint: true },
  },
  {
    id: "discord.gateway",
    name: "manage_discord_gateway",
    description: "Manage the Discord Gateway WebSocket connection. Actions: 'status' — check if the gateway is connected, get bot user ID, session info, and pending responses. 'restart' — disconnect the current gateway and reconnect with a fresh token from the vault (use after updating the bot token via secrets.prompt_user). 'stop' — shut down the gateway gracefully.",
    source: "core",
    category: "discord",
    executor: "local",
    runtime: "internal",
    inputSchema: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["status", "restart", "stop"], description: "The gateway management action to perform" },
      },
      required: ["action"],
    },
    annotations: { mutatingHint: true },
  },
  {
    id: "discord.full_setup",
    name: "full_discord_setup",
    description: "One-shot Discord setup: creates a bot-owned server, sets up #conversation/#updates/#logs channels, generates an invite link + QR code, and writes all config to ~/.bot/.env. Smart resume — detects existing bot-owned server and channels, skips what's already done. Call this AFTER the token is validated with discord.validate_token. Returns the invite URL and QR code for the user to join.",
    source: "core",
    category: "discord",
    executor: "local",
    runtime: "internal",
    credentialRequired: "DISCORD_BOT_TOKEN",
    inputSchema: {
      type: "object",
      properties: {
        name: { type: "string", description: "Server name (default: 'Agent HQ')" },
      },
    },
    annotations: { destructiveHint: true, mutatingHint: true },
  },
];
