/**
 * Browser Setup Server
 *
 * Runs a local HTTP server on the client machine to facilitate secure browser authentication.
 * Instead of saving the bearer token to filesystem (where prompt injection could read it),
 * we issue device-scoped session cookies directly to the browser.
 */

import express, { Request, Response } from 'express';
import { randomBytes, createCipheriv, createDecipheriv } from 'crypto';
import * as path from 'path';
import { createComponentLogger } from './logging.js';

let _log: ReturnType<typeof createComponentLogger> | null = null;
function log() {
  if (!_log) _log = createComponentLogger('setup-server');
  return _log;
}

// Encryption key for session cookies (ephemeral, generated on agent start)
const SESSION_KEY = randomBytes(32);
const ALGORITHM = 'aes-256-gcm';

/**
 * Encrypt device credentials for session cookie
 */
function encryptSession(deviceId: string, deviceSecret: string): string {
  const iv = randomBytes(16);
  const cipher = createCipheriv(ALGORITHM, SESSION_KEY, iv);

  const payload = JSON.stringify({ deviceId, deviceSecret });
  let encrypted = cipher.update(payload, 'utf8', 'hex');
  encrypted += cipher.final('hex');

  const authTag = cipher.getAuthTag();

  // Format: iv:authTag:encrypted
  return `${iv.toString('hex')}:${authTag.toString('hex')}:${encrypted}`;
}

/**
 * Decrypt session cookie back to device credentials
 */
export function decryptSession(encryptedSession: string): { deviceId: string; deviceSecret: string } | null {
  try {
    const [ivHex, authTagHex, encrypted] = encryptedSession.split(':');
    if (!ivHex || !authTagHex || !encrypted) return null;

    const iv = Buffer.from(ivHex, 'hex');
    const authTag = Buffer.from(authTagHex, 'hex');
    const decipher = createDecipheriv(ALGORITHM, SESSION_KEY, iv);
    decipher.setAuthTag(authTag);

    let decrypted = decipher.update(encrypted, 'hex', 'utf8');
    decrypted += decipher.final('utf8');

    return JSON.parse(decrypted);
  } catch {
    return null;
  }
}

/**
 * Start local HTTP server for browser setup
 */
export function startSetupServer(
  deviceId: string,
  deviceSecret: string,
  serverUrl: string
): { port: number; setupCode: string } {
  const app = express();
  const port = findAvailablePort();
  const setupCode = randomBytes(8).toString('hex');
  let codeUsed = false;

  // Derive WebSocket URL from HTTP URL (reverse of the conversion in index.ts)
  const wsUrl = serverUrl.replace(/^https?:\/\//, (match) => match === 'https://' ? 'wss://' : 'ws://') + '/ws';

  // Resolve local client directory for static serving
  const clientDir = path.resolve('client');

  // Serve dynamic config.js with device credentials (only after setup validation)
  let authenticated = false;
  app.get('/config.js', (_req: Request, res: Response) => {
    if (!authenticated) {
      return res.status(403).type('text/javascript').send('// Not authenticated');
    }
    res.type('text/javascript').send(
      `// Auto-generated by setup server\nwindow.DOTBOT_CONFIG = { wsUrl: '${wsUrl}', deviceId: '${deviceId}', deviceSecret: '${deviceSecret}' };`
    );
  });

  // Serve client directory as static files (index.html loads config.js from same origin)
  app.use(express.static(clientDir));

  // Setup endpoint - validates code and redirects to client served over HTTP
  app.get('/setup', (req: Request, res: Response) => {
    if (req.query.code !== setupCode) {
      log().warn('Invalid setup code attempt', { ip: req.ip });
      return res.status(403).send(`
        <html>
          <head><title>Setup Failed</title></head>
          <body style="font-family: system-ui; max-width: 600px; margin: 100px auto; text-align: center;">
            <h1>Setup Failed</h1>
            <p>Invalid or expired setup code. Please use the setup link provided by the agent.</p>
          </body>
        </html>
      `);
    }

    if (codeUsed) {
      return res.status(403).send(`
        <html>
          <head><title>Setup Code Used</title></head>
          <body style="font-family: system-ui; max-width: 600px; margin: 100px auto; text-align: center;">
            <h1>Already Used</h1>
            <p>This setup code has already been used. Restart the agent for a new one.</p>
          </body>
        </html>
      `);
    }

    codeUsed = true;
    authenticated = true;
    log().info('Setup code validated, serving client with credentials');

    // Redirect to client served from this same localhost server
    // config.js is now served dynamically with credentials
    res.redirect('/index.html');
  });

  // Health check
  app.get('/health', (_req: Request, res: Response) => {
    res.json({ status: 'ok', deviceId });
  });

  // Start server
  const server = app.listen(port, 'localhost', () => {
    log().info(`Setup server started on http://localhost:${port}`);
  });

  // Handle errors
  server.on('error', (err: Error) => {
    log().error('Setup server error', { error: err });
  });

  return { port, setupCode };
}

/**
 * Find an available port for the setup server
 */
function findAvailablePort(): number {
  // Use a random port in the ephemeral range
  return 49152 + Math.floor(Math.random() * (65535 - 49152));
}
