/**
 * Filesystem Tool Definitions
 */

import type { DotBotTool } from "../../memory/types.js";

export const filesystemTools: DotBotTool[] = [
  {
    id: "filesystem.create_file",
    name: "create_file",
    description: "Create a new file with the specified content. Creates parent directories if needed. Use ~/ for user home paths.",
    source: "core",
    category: "filesystem",
    executor: "local",
    runtime: "internal",
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string", description: "Full file path (e.g., ~/Desktop/hello.txt)" },
        content: { type: "string", description: "Content to write to the file" },
      },
      required: ["path", "content"],
    },
    annotations: { destructiveHint: true },
  },
  {
    id: "filesystem.read_file",
    name: "read_file",
    description: "Read the contents of a file. Returns the full text content.",
    source: "core",
    category: "filesystem",
    executor: "local",
    runtime: "internal",
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string", description: "Full file path to read" },
      },
      required: ["path"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    id: "filesystem.read_file_base64",
    name: "read_file_base64",
    description: "Read a file and return its contents as a base64-encoded string. Use for binary files (images, PDFs, etc.) that need to be transferred or embedded.",
    source: "core",
    category: "filesystem",
    executor: "local",
    runtime: "internal",
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string", description: "Full file path to read" },
      },
      required: ["path"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    id: "filesystem.upload_file",
    name: "upload_file",
    description: "Upload a local file to a remote URL via multipart POST. Use for sending files to APIs, webhooks, or upload endpoints.",
    source: "core",
    category: "filesystem",
    executor: "local",
    runtime: "internal",
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string", description: "Local file path to upload" },
        uploadUrl: { type: "string", description: "Remote URL to upload to" },
        source: { type: "string", description: "Optional source identifier sent with the upload" },
      },
      required: ["path", "uploadUrl"],
    },
    annotations: {},
  },
  {
    id: "filesystem.append_file",
    name: "append_file",
    description: "Append content to the end of an existing file. Creates the file if it doesn't exist.",
    source: "core",
    category: "filesystem",
    executor: "local",
    runtime: "internal",
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string", description: "Full file path to append to" },
        content: { type: "string", description: "Content to append" },
      },
      required: ["path", "content"],
    },
    annotations: { destructiveHint: true },
  },
  {
    id: "filesystem.delete_file",
    name: "delete_file",
    description: "Delete a file. Does not delete directories — use directory.delete for that.",
    source: "core",
    category: "filesystem",
    executor: "local",
    runtime: "internal",
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string", description: "Full file path to delete" },
      },
      required: ["path"],
    },
    annotations: { destructiveHint: true, requiresConfirmation: true },
  },
  {
    id: "filesystem.move",
    name: "move_file",
    description: "Move or rename a file or directory.",
    source: "core",
    category: "filesystem",
    executor: "local",
    runtime: "powershell",
    inputSchema: {
      type: "object",
      properties: {
        source: { type: "string", description: "Source path" },
        destination: { type: "string", description: "Destination path" },
      },
      required: ["source", "destination"],
    },
    annotations: { destructiveHint: true },
  },
  {
    id: "filesystem.copy",
    name: "copy_file",
    description: "Copy a file or directory to a new location.",
    source: "core",
    category: "filesystem",
    executor: "local",
    runtime: "powershell",
    inputSchema: {
      type: "object",
      properties: {
        source: { type: "string", description: "Source path" },
        destination: { type: "string", description: "Destination path" },
        recurse: { type: "boolean", description: "Copy directories recursively (default: true)" },
      },
      required: ["source", "destination"],
    },
    annotations: {},
  },
  {
    id: "filesystem.exists",
    name: "file_exists",
    description: "Check if a file or directory exists at the given path.",
    source: "core",
    category: "filesystem",
    executor: "local",
    runtime: "internal",
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string", description: "Path to check" },
      },
      required: ["path"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    id: "filesystem.edit_file",
    name: "edit_file",
    description: "Make a targeted edit to a file by finding and replacing a specific string. Much more efficient than rewriting the entire file. The old_string must match exactly (including whitespace and indentation). Use replace_all to replace every occurrence.",
    source: "core",
    category: "filesystem",
    executor: "local",
    runtime: "internal",
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string", description: "Full file path to edit" },
        old_string: { type: "string", description: "Exact text to find in the file (must be unique unless replace_all is true)" },
        new_string: { type: "string", description: "Text to replace it with" },
        replace_all: { type: "boolean", description: "Replace all occurrences, not just the first (default: false)" },
      },
      required: ["path", "old_string", "new_string"],
    },
    annotations: { destructiveHint: true },
  },
  {
    id: "filesystem.read_lines",
    name: "read_lines",
    description: "Read specific lines from a file by line number range. Returns lines with line numbers prefixed. Use this instead of read_file for large files — read only the section you need.",
    source: "core",
    category: "filesystem",
    executor: "local",
    runtime: "internal",
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string", description: "Full file path to read" },
        start_line: { type: "number", description: "First line to read (1-indexed)" },
        end_line: { type: "number", description: "Last line to read (inclusive). Omit to read to end of file." },
      },
      required: ["path", "start_line"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    id: "filesystem.diff",
    name: "diff_files",
    description: "Compare two files and show the differences in unified diff format. Use this to verify that edits were applied correctly, compare a file before/after changes, or diff a workspace copy against the live version. Can also compare a file against a string.",
    source: "core",
    category: "filesystem",
    executor: "local",
    runtime: "internal",
    inputSchema: {
      type: "object",
      properties: {
        path_a: { type: "string", description: "Path to the first file (the 'before' or 'original')" },
        path_b: { type: "string", description: "Path to the second file (the 'after' or 'modified')" },
        content_b: { type: "string", description: "Alternative to path_b: compare path_a against this string content instead of a second file" },
        context_lines: { type: "number", description: "Number of context lines around each change (default: 3)" },
      },
      required: ["path_a"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    id: "filesystem.file_info",
    name: "file_info",
    description: "Get metadata about a file: size, creation date, modification date, type.",
    source: "core",
    category: "filesystem",
    executor: "local",
    runtime: "internal",
    inputSchema: {
      type: "object",
      properties: {
        path: { type: "string", description: "Path to inspect" },
      },
      required: ["path"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    id: "filesystem.download",
    name: "download_file",
    description: "Download a file from a URL and save it to disk. Handles binary files (images, installers, archives) and text. Shows progress for large downloads. Use this instead of http_request when you need to save a file rather than read its content.",
    source: "core",
    category: "filesystem",
    executor: "local",
    runtime: "internal",
    inputSchema: {
      type: "object",
      properties: {
        url: { type: "string", description: "URL to download from" },
        path: { type: "string", description: "Local file path to save to" },
        timeout_seconds: { type: "number", description: "Max seconds to wait (default: 120, max: 600)" },
      },
      required: ["url", "path"],
    },
    annotations: { destructiveHint: true },
  },
  {
    id: "filesystem.archive",
    name: "create_archive",
    description: "Create a zip archive from files or directories. Use for backups, packaging deployments, or compressing files for transfer.",
    source: "core",
    category: "filesystem",
    executor: "local",
    runtime: "internal",
    inputSchema: {
      type: "object",
      properties: {
        source: { type: "string", description: "Path to file or directory to archive" },
        destination: { type: "string", description: "Path for the output .zip file" },
      },
      required: ["source", "destination"],
    },
    annotations: { destructiveHint: true },
  },
  {
    id: "filesystem.extract",
    name: "extract_archive",
    description: "Extract a zip archive to a directory. Handles .zip files. Creates the destination directory if needed.",
    source: "core",
    category: "filesystem",
    executor: "local",
    runtime: "internal",
    inputSchema: {
      type: "object",
      properties: {
        source: { type: "string", description: "Path to the .zip archive" },
        destination: { type: "string", description: "Directory to extract into" },
      },
      required: ["source", "destination"],
    },
    annotations: { destructiveHint: true },
  },
];
